blank_issues_enabled: false
issue_templates:
  - name: "Add known wiki"
    description: "Request to add a known wiki"
    title:"[newwiki]: <wiki URL>"
    body: newwiki.md
  - name: "Bug report"
    description: "Bug report. Be descriptive and precise."
    title: "[Bug] Bug report: "